port: 7890
mixed-port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7893
routing-mark: 6666
allow-lan: true
bind-address: "*"
mode: rule
log-level: debug # 日志等级 silent/error/warning/info/debug
external-controller: 0.0.0.0:9090
secret: ''
external-ui: ui
external-ui-name: zashboard
external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages-cdn-fonts.zip"
geodata-mode: true
geodata-loader: memconservative
find-process-mode: strict
tcp-concurrent: true
global-client-fingerprint: chrome
disable-keep-alive: false #目前在android端强制为true
keep-alive-idle: 15
keep-alive-interval: 600
unified-delay: true
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  asn: "https://cdn.jsdelivr.net/gh/P3TERX/GeoLite.mmdb@download/GeoLite2-ASN.mmdb"
geo-auto-update: true # 是否自动更新 geo
geo-update-interval: 24 # 更新间隔，单位：小时
# GeoSite 使用的匹配器实现，可用的实现：
# - succinct （默认，与规则集相同）
# - mph （来自 V2Ray，在 Xray 中也是“混合”）
geosite-matcher: succinct
global-ua: clash.meta
etag-support: true
experimental:
  ignore-resolve-fail: true
  sniff-tls-sni: true
  udp-fallback-match: true
  quic-go-disable-gso: true
profile:
  store-fake-ip: true
  store-selected: true
  tracing: true
ipv6: true
dns:
  cache-algorithm: arc
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:7874
  ipv6: true
  use-hosts: true
  respect-rules: false
  default-nameserver:
    - tls://223.5.5.5:853
    - https://120.53.53.53/dns-query
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-range6: 2001:db9::1/64
  fake-ip-filter-mode: blacklist
  fake-ip-ttl: 1
  fake-ip-filter:
    # 基础域名后缀 - 私有网络和保留域名
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - "*.direct"
    # 连接性检测
    - "network-test.debian.org"
    - "detectportal.firefox.com"
    - "resolver1.opendns.com"
    # WiFi Calling  
    - "+.pub.3gppnetwork.org"
    # Apple 更新服务
    - "mesu.apple.com"
    - "swscan.apple.com"
    - "swquery.apple.com"
    - "swdownload.apple.com"
    - "swcdn.apple.com"
    - "swdist.apple.com"
    # 流媒体 CDN
    - "+.nflxvideo.net"
    - "*.mcdn.bilivideo.cn"
    - "+.media.dssott.com"
    # STUN/NTP/时间服务 - 关键字匹配
    - "+.pool.ntp.org"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    # STUN 服务器 - P2P连接和视频通话必需
    - "+.stun.l.google.com"
    - "+.global.stun.twilio.com"
    - "stun.cloudflare.com"
    - "+.stun.playstation.net"
    - "stun.*.*"
    - "stun.*.*.*"
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"
    # 游戏平台特定域名
    - "+.steamcontent.com"
    - "+.wotgame.cn"
    - "+.wggames.cn"
    - "+.wowsgame.cn"
    - "+.wargaming.net"
    # Nintendo Switch
    - "+.srv.nintendo.net"
    - "*.n.n.srv.nintendo.net"
    - "+.cdn.nintendo.net"
    # Google 服务
    - "lens.l.google.com"
    - "na.b.g-tun.com"
    # 招商银行
    - "+.cmbchina.com"
    - "+.cmbimg.com"
    # AdGuard 本地服务
    - "local.adguard.org"
    # 迅雷下载
    - "+.sandai.net"
    - "+.n0808.com"
    # 网易 UU 加速器
    - "+.uu.163.com"
    - "ps.res.netease.com"
    # 使用 geosite/geoip 引用，自动包含所有相关域名和IP
    - geosite:private  # 私有网络域名（路由器、局域网设备、STUN服务器等）
    - geosite:category-games@cn  # 中国游戏平台（所有国内游戏服务器）
    - geoip:private  # 私有IP地址段（192.168.x.x, 10.x.x.x, 127.x.x.x等）
  nameserver:
    - https://v.recipes/dns-cn#h3=true&skip-cert-verify=true
    - https://sm2.doh.pub/dns-query#h3=true&skip-cert-verify=true
    - quic://dns.alidns.com:853#skip-cert-verify=true
  fallback:
    - https://v.recipes/dns/secondary.dns.seia.io/dns-query#h3=true&skip-cert-verify=true
    - https://v.recipes/dns/dns.google/dns-query#h3=true&skip-cert-verify=true
    - https://v.recipes/dns/doh.dns.sb/dns-query#h3=true&skip-cert-verify=true
  proxy-server-nameserver:
    - https://v.recipes/dns/secondary.dns.seia.io/dns-query#h3=true&skip-cert-verify=true
    - https://v.recipes/dns/dns.google/dns-query#h3=true&skip-cert-verify=true
    - https://v.recipes/dns/doh.dns.sb/dns-query#h3=true&skip-cert-verify=true
    - https://v.recipes/dns-cn#h3=true&skip-cert-verify=true
    - https://sm2.doh.pub/dns-query#h3=true&skip-cert-verify=true
    - quic://dns.alidns.com:853#skip-cert-verify=true
  direct-nameserver:
    - https://v.recipes/dns-cn#h3=true&skip-cert-verify=true
    - https://sm2.doh.pub/dns-query#h3=true&skip-cert-verify=true
    - quic://dns.alidns.com:853#skip-cert-verify=true
  direct-nameserver-follow-policy: true
  fallback-filter:
    geoip: true
    geoip-code: CN  # 如果国内DNS返回国内IP则放行，否则使用fallback
    geosite:
      - geolocation-!cn  # 非中国网站强制使用fallback DNS
    ipcidr:
      # 使用 geoip:private 替代手动列举私有IP
      - geoip:private
    domain:
      # 关键国际服务域名强制使用fallback DNS
      - "+.google.com"
      - "+.googleapis.com"
      - "+.googlevideo.com"
      - "+.gstatic.com"
      - "+.facebook.com"
      - "+.youtube.com"
      - "+.github.com"
      - "+.githubusercontent.com"
  proxy-server-nameserver-policy:
    "+.ndmdhs.com": 1.0.0.1
    "+.dutils.com": 114.114.114.114
    "+.hostbuf.com": 114.114.114.114
    "geosite:category-ads-all": rcode://success
    "++.tw,+.jp":
      - https://v.recipes/dns/secondary.dns.seia.io/dns-query#h3=true&skip-cert-verify=true
      - https://v.recipes/dns/dns.google/dns-query#h3=true&skip-cert-verify=true
      - https://v.recipes/dns/doh.dns.sb/dns-query#h3=true&skip-cert-verify=true
      - https://v.recipes/dns-ecs
    "geosite:category-games@cn":
      - https://v.recipes/dns-cn#h3=true&skip-cert-verify=true
      - https://sm2.doh.pub/dns-query#h3=true&skip-cert-verify=true
      - quic://dns.alidns.com:853#skip-cert-verify=true
    "rule-set:WeChat,DNS":
      - https://v.recipes/dns-cn#h3=true&skip-cert-verify=true
      - https://sm2.doh.pub/dns-query#h3=true&skip-cert-verify=true
      - quic://dns.alidns.com:853#skip-cert-verify=true
    "rule-set:AppleMusic,AMusic":
      - https://v.recipes/dns/secondary.dns.seia.io/dns-query#h3=true&skip-cert-verify=true
      - https://v.recipes/dns/dns.google/dns-query#h3=true&skip-cert-verify=true
      - https://v.recipes/dns/doh.dns.sb/dns-query#h3=true&skip-cert-verify=true
      - https://v.recipes/dns-ecs
    "geosite:category-ai-!cn,geolocation-!cn":
      - https://v.recipes/dns/secondary.dns.seia.io/dns-query#h3=true&skip-cert-verify=true
      - https://v.recipes/dns/dns.google/dns-query#h3=true&skip-cert-verify=true
      - https://v.recipes/dns/doh.dns.sb/dns-query#h3=true&skip-cert-verify=true
      - https://v.recipes/dns-ecs
    "geosite:apple,cloudflare,wikimedia,tiktok,pikpak,github,speedtest,sony,meta,google,microsoft,yahoo":
      - https://v.recipes/dns/secondary.dns.seia.io/dns-query#h3=true&skip-cert-verify=true
      - https://v.recipes/dns/dns.google/dns-query#h3=true&skip-cert-verify=true
      - https://v.recipes/dns/doh.dns.sb/dns-query#h3=true&skip-cert-verify=true
      - https://v.recipes/dns-ecs
    "geosite:apple-cn,cn,private":
      - https://v.recipes/dns-cn#h3=true&skip-cert-verify=true
      - https://sm2.doh.pub/dns-query#h3=true&skip-cert-verify=true
      - quic://dns.alidns.com:853#skip-cert-verify=true
    "geoip:google":
      - https://v.recipes/dns/secondary.dns.seia.io/dns-query#h3=true&skip-cert-verify=true
      - https://v.recipes/dns/dns.google/dns-query#h3=true&skip-cert-verify=true
      - https://v.recipes/dns/doh.dns.sb/dns-query#h3=true&skip-cert-verify=true
      - https://v.recipes/dns-ecs
    "geoip:cn":
      - quic://223.5.5.5:853#skip-cert-verify=true
      - https://1.12.12.12/dns-query#h3=true&skip-cert-verify=true
  nameserver-policy:
    "+.ndmdhs.com": 1.0.0.1
    "+.dutils.com": 114.114.114.114
    "+.hostbuf.com": 114.114.114.114
    "geosite:category-ads-all": rcode://success
    "++.tw,+.jp":
      - https://v.recipes/dns/secondary.dns.seia.io/dns-query
      - https://v.recipes/dns/dns.google/dns-query
      - https://v.recipes/dns/doh.dns.sb/dns-query
      - https://v.recipes/dns-ecs
    "geosite:category-games@cn":
      - https://v.recipes/dns-cn
      - https://sm2.doh.pub/dns-query
      - quic://dns.alidns.com:853
    "rule-set:WeChat,DNS":
      - https://v.recipes/dns-cn
      - https://sm2.doh.pub/dns-query
      - quic://dns.alidns.com:853
    "rule-set:AppleMusic,AMusic":
      - https://v.recipes/dns/secondary.dns.seia.io/dns-query
      - https://v.recipes/dns/dns.google/dns-query
      - https://v.recipes/dns/doh.dns.sb/dns-query
      - https://v.recipes/dns-ecs
    "geosite:category-ai-!cn,geolocation-!cn":
      - https://v.recipes/dns/secondary.dns.seia.io/dns-query
      - https://v.recipes/dns/dns.google/dns-query
      - https://v.recipes/dns/doh.dns.sb/dns-query
      - https://v.recipes/dns-ecs
    "geosite:apple,cloudflare,wikimedia,tiktok,pikpak,github,speedtest,sony,meta,google,microsoft,yahoo":
      - https://v.recipes/dns/secondary.dns.seia.io/dns-query
      - https://v.recipes/dns/dns.google/dns-query
      - https://v.recipes/dns/doh.dns.sb/dns-query
      - https://v.recipes/dns-ecs
    "geosite:apple-cn,cn,private":
      - https://v.recipes/dns-cn
      - https://sm2.doh.pub/dns-query
      - quic://dns.alidns.com:853
    "geoip:google":
      - https://v.recipes/dns/secondary.dns.seia.io/dns-query
      - https://v.recipes/dns/dns.google/dns-query
      - https://v.recipes/dns/doh.dns.sb/dns-query
      - https://v.recipes/dns-ecs
    "geoip:cn":
      - quic://223.5.5.5:853
      - https://1.12.12.12/dns-query
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    QUIC:
      ports: [443, 8443]
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
  force-domain:
    - geosite:geolocation-!cn
  skip-domain:
    - Mijia Cloud
    - +.mijia.tech
    - dlg.io.mi.com
    - +.oray.com
    - +.sunlogin.net
    - geosite:cn