port: 7890
mixed-port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7893
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
secret: ''
external-ui: /path/to/ui/folder
external-ui-name: metacubexd
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
geodata-mode: true
geodata-loader: memconservative
find-process-mode: strict
tcp-concurrent: true
global-client-fingerprint: chrome
keep-alive-interval: 15
unified-delay: true
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
geo-auto-update: false # 是否自动更新 geo
geo-update-interval: 24
experimental:
  ignore-resolve-fail: true
  sniff-tls-sni: true
  udp-fallback-match: true
profile:
  store-fake-ip: true
  store-selected: true
  tracing: true
ipv6: true
hosts:
  mtalk.google.com: 108.177.125.188
  raw.githubusercontent.com: 151.101.76.133
dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:7874
  ipv6: true
  use-hosts: true
  respect-rules: false
  default-nameserver:
    - 114.114.114.144
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "*.example"
    - "*.home.arpa"
    - "*.invalid"
    - "*.lan"
    - "*.local"
    - "*.localdomain"
    - "*.localhost"
    - "*.test"
    - mesu.apple.com
    - swscan.apple.com
    - "*.router.asus.com"
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.ipv6.microsoft.com"
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - time.*.apple.com
    - time.*.com
    - time.*.gov
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - time.*.edu.cn
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - Mijia Cloud
    - +.mijia.tech
    - time-ios.apple.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "+.qq.com"
    - "+.tencent.com"
    - "+.srv.nintendo.net"
    - "*.n.n.srv.nintendo.net"
    - "+.cdn.nintendo.net"
    - "+.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - "+.battlenet.com.cn"
    - "+.wotgame.cn"
    - "+.wggames.cn"
    - "+.wowsgame.cn"
    - "+.wargaming.net"
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"
    - heartbeat.belkin.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - na.b.g-tun.com
    - "+.nflxvideo.net"
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "*.ff14.sdo.com"
    - ff.dorado.sdo.com
    - "*.mcdn.bilivideo.cn"
    - "+.media.dssott.com"
    - shark007.net
    - "+.cmbchina.com"
    - "+.cmbimg.com"
    - local.adguard.org
    - "+.sandai.net"
    - "+.n0808.com"
    - "+.uu.163.com"
    - ps.res.netease.com
    - geosite:category-games
    - geosite:cn
    - geoip:cn
  nameserver:
     - https://doh.pub/dns-query
     - https://dns.alidns.com/dns-query
  fallback:
     - https://dns.google/dns-query
     - https://dns.cloudflare.com/dns-query
  proxy-server-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.cloudflare.com/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
       - gfw
       - geolocation-!cn
    ipcidr:
       - 0.0.0.0/32
       - 100.64.0.0/10
       - 127.0.0.0/8
       - 240.0.0.0/4
       - 255.255.255.255/32
    domain:
       - "+.google.com"
       - "+.facebook.com"
       - "+.youtube.com"
       - "+.google.cn"
       - "+.googleapis.cn"
       - "+.translate.googleapis.com"
       - "+.safebrowsing.googleapis.com"
       - "+.clientservices.googleapis.com"
       - "+.bing.com"
       - "+.linkedin.com"
       - "+.msn.cn"
       - "+.playstationnetwork.com"
       - "+.sony.com"
       - "+.sonyentertainmentnetwork.com"
       - "+.playstation.com"
       - ".ac"
       - ".ad"
       - ".ae"
       - ".aero"
       - ".af"
       - ".ag"
       - ".ai"
       - ".al"
       - ".am"
       - ".ao"
       - ".app"
       - ".aq"
       - ".ar"
       - ".art"
       - ".as"
       - ".asia"
       - ".at"
       - ".au"
       - ".aw"
       - ".ax"
       - ".az"
       - ".ba"
       - ".bar"
       - ".bb"
       - ".bd"
       - ".be"
       - ".beauty"
       - ".best"
       - ".bf"
       - ".bg"
       - ".bh"
       - ".bi"
       - ".bible"
       - ".biz"
       - ".bj"
       - ".bm"
       - ".bn"
       - ".bo"
       - ".br"
       - ".bs"
       - ".bt"
       - ".buzz"
       - ".bw"
       - ".by"
       - ".bz"
       - ".ca"
       - ".cat"
       - ".catholic"
       - ".cd"
       - ".cf"
       - ".cg"
       - ".ch"
       - ".chat"
       - ".church"
       - ".ci"
       - ".ck"
       - ".cl"
       - ".cloud"
       - ".club"
       - ".cm"
       - ".co"
       - ".college"
       - ".company"
       - ".cool"
       - ".coop"
       - ".cr"
       - ".cu"
       - ".cv"
       - ".cw"
       - ".cx"
       - ".cy"
       - ".cyou"
       - ".cz"
       - ".day"
       - ".de"
       - ".design"
       - ".dev"
       - ".digital"
       - ".dj"
       - ".dk"
       - ".dm"
       - ".do"
       - ".dog"
       - ".download"
       - ".dz"
       - ".earth"
       - ".ec"
       - ".eco"
       - ".edu"
       - ".ee"
       - ".eg"
       - ".er"
       - ".es"
       - ".et"
       - ".eu"
       - ".eu.org"
       - ".fi"
       - ".fit"
       - ".fj"
       - ".fk"
       - ".fm"
       - ".fo"
       - ".fr"
       - ".fun"
       - ".fyi"
       - ".ga"
       - ".game"
       - ".gay"
       - ".gd"
       - ".ge"
       - ".gf"
       - ".gg"
       - ".gh"
       - ".gi"
       - ".gl"
       - ".glass"
       - ".global"
       - ".gm"
       - ".gn"
       - ".google"
       - ".gov"
       - ".gp"
       - ".gq"
       - ".gr"
       - ".green"
       - ".gs"
       - ".gt"
       - ".gu"
       - ".gw"
       - ".gy"
       - ".health"
       - ".hk"
       - ".hm"
       - ".hn"
       - ".homes"
       - ".host"
       - ".hr"
       - ".ht"
       - ".hu"
       - ".icu"
       - ".id"
       - ".ie"
       - ".il"
       - ".im"
       - ".in"
       - ".inc"
       - ".info"
       - ".ink"
       - ".int"
       - ".iq"
       - ".ir"
       - ".is"
       - ".it"
       - ".je"
       - ".jm"
       - ".jo"
       - ".jobs"
       - ".jp"
       - ".ke"
       - ".kg"
       - ".kh"
       - ".ki"
       - ".kid"
       - ".km"
       - ".kn"
       - ".kp"
       - ".kr"
       - ".kw"
       - ".ky"
       - ".kz"
       - ".la"
       - ".lb"
       - ".lc"
       - ".li"
       - ".life"
       - ".link"
       - ".live"
       - ".lk"
       - ".loan"
       - ".lol"
       - ".love"
       - ".lr"
       - ".ls"
       - ".lt"
       - ".lu"
       - ".lv"
       - ".ly"
       - ".ma"
       - ".mc"
       - ".md"
       - ".me"
       - ".media"
       - ".men"
       - ".mg"
       - ".mh"
       - ".mil"
       - ".mk"
       - ".ml"
       - ".mm"
       - ".mn"
       - ".mo"
       - ".mobi"
       - ".moe"
       - ".monster"
       - ".mp"
       - ".mq"
       - ".mr"
       - ".ms"
       - ".mt"
       - ".mu"
       - ".museum"
       - ".mv"
       - ".mw"
       - ".mx"
       - ".my"
       - ".mz"
       - ".na"
       - ".name"
       - ".nc"
       - ".ne"
       - ".network"
       - ".nf"
       - ".ng"
       - ".ni"
       - ".nl"
       - ".no"
       - ".np"
       - ".nr"
       - ".nu"
       - ".nz"
       - ".om"
       - ".one"
       - ".online"
       - ".ooo"
       - ".pa"
       - ".pe"
       - ".pf"
       - ".pg"
       - ".ph"
       - ".pics"
       - ".pk"
       - ".pl"
       - ".pm"
       - ".pn"
       - ".post"
       - ".pr"
       - ".pro"
       - ".ps"
       - ".pt"
       - ".pub"
       - ".pw"
       - ".py"
       - ".qa"
       - ".quest"
       - ".re"
       - ".rest"
       - ".rip"
       - ".ro"
       - ".rocks"
       - ".rs"
       - ".ru"
       - ".run"
       - ".rw"
       - ".sa"
       - ".sb"
       - ".sbs"
       - ".sc"
       - ".sd"
       - ".se"
       - ".sex"
       - ".sg"
       - ".sh"
       - ".shop"
       - ".si"
       - ".site"
       - ".sk"
       - ".sl"
       - ".sm"
       - ".sn"
       - ".so"
       - ".space"
       - ".sr"
       - ".ss"
       - ".st"
       - ".store"
       - ".su"
       - ".sv"
       - ".sx"
       - ".sy"
       - ".sz"
       - ".tc"
       - ".td"
       - ".team"
       - ".tech"
       - ".tel"
       - ".tf"
       - ".tg"
       - ".th"
       - ".tj"
       - ".tk"
       - ".tl"
       - ".tm"
       - ".tn"
       - ".to"
       - ".today"
       - ".tokyo"
       - ".top"
       - ".tr"
       - ".travel"
       - ".tt"
       - ".tv"
       - ".tw"
       - ".tz"
       - ".ua"
       - ".ug"
       - ".uk"
       - ".uno"
       - ".us"
       - ".uy"
       - ".uz"
       - ".va"
       - ".vc"
       - ".ve"
       - ".vg"
       - ".vi"
       - ".video"
       - ".vip"
       - ".vn"
       - ".vu"
       - ".website"
       - ".wf"
       - ".wiki"
       - ".win"
       - ".work"
       - ".ws"
       - ".wtf"
       - ".xxx"
       - ".xyz"
       - ".ye"
       - ".yt"
       - ".za"
       - ".zm"
       - ".zone"
       - ".zw"
  nameserver-policy:
    "+.ndmdhs.com": 1.0.0.1
    "+.dutils.com": 114.114.114.114
    "+.hostbuf.com": 114.114.114.114
    "+.tw":
        - https://dns.cloudflare.com/dns-query
        - https://dns.google/dns-query
    geosite:category-games@cn:
        - https://dns.alidns.com/dns-query
        - https://doh.pub/dns-query
    geosite:github,speedtest,sony,microsoft,yahoo,gfw,geolocation-!cn:
        - https://dns.cloudflare.com/dns-query
        - https://dns.google/dns-query
    geosite:cn,private,apple:
        - https://dns.alidns.com/dns-query
        - https://doh.pub/dns-query
    geosite:category-ads-all: rcode://success
    geoip:cn:
        - https://dns.alidns.com/dns-query
        - https://doh.pub/dns-query
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    QUIC:
      ports: [443, 8443]
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
  skip-domain:
    - Mijia Cloud
    - +.mijia.tech
