port: 7890
mixed-port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7893
routing-mark: 6666
allow-lan: true
bind-address: "*"
mode: rule
log-level: debug # 日志等级 silent/error/warning/info/debug
external-controller: 0.0.0.0:9090
secret: ''
external-ui: ui
external-ui-name: zashboard
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist-cdn-fonts.zip"
geodata-mode: true
geodata-loader: memconservative
find-process-mode: strict
tcp-concurrent: true
global-client-fingerprint: chrome
disable-keep-alive: false #目前在android端强制为true
keep-alive-idle: 15
keep-alive-interval: 600
unified-delay: true
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  asn: "https://cdn.jsdelivr.net/gh/P3TERX/GeoLite.mmdb@download/GeoLite2-ASN.mmdb"
geo-auto-update: true # 是否自动更新 geo
geo-update-interval: 24 # 更新间隔，单位：小时
# GeoSite 使用的匹配器实现，可用的实现：
# - succinct （默认，与规则集相同）
# - mph （来自 V2Ray，在 Xray 中也是“混合”）
geosite-matcher: succinct
global-ua: clash.meta
etag-support: true
experimental:
  ignore-resolve-fail: true
  sniff-tls-sni: true
  udp-fallback-match: true
profile:
  store-fake-ip: true
  store-selected: true
  tracing: true
ipv6: true
hosts:
  github.com: 140.82.121.4
  raw.githubusercontent.com: 185.199.108.133
  objects.githubusercontent.com: 185.199.110.133
  github.githubassets.com: 185.199.109.154
dns:
  cache-algorithm: arc
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:7874
  ipv6: true
  use-hosts: true
  respect-rules: false
  default-nameserver:
    - tls://223.5.5.5:853
    - https://120.53.53.53/dns-query
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - "*.direct"
    - cable.auth.com
    - network-test.debian.org
    - detectportal.firefox.com
    - resolver1.opendns.com
    - global.turn.twilio.com
    - global.stun.twilio.com
    - app.yinxiang.com
    - injections.adguard.org
    - localhost.*.weixin.qq.com
    - "*.blzstatic.cn"
    - "*.cmpassport.com"
    - id6.me
    - open.e.189.cn
    - opencloud.wostore.cn
    - id.mail.wo.cn
    - mdn.open.wo.cn
    - hmrz.wo.cn
    - nishub1.10010.com
    - enrichgw.10010.com
    - "*.wosms.cn"
    - "*.jegotrip.com.cn"
    - "*.icitymobile.mobi"
    - "*.pingan.com.cn"
    - "*.cmbchina.com"
    - "*.10099.com.cn"
    - "*.microdone.cn"
    - PDC._msDCS.*.*
    - DC._msDCS.*.*
    - GC._msDCS.*.*
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time-ios.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - "+.pool.ntp.org"
    - time1.cloud.tencent.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - "+.qq.com"
    - "+.tencent.com"
    - "+.srv.nintendo.net"
    - "*.n.n.srv.nintendo.net"
    - "+.cdn.nintendo.net"
    - "+.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - "+.battle.net"
    - "+.battlenet.com.cn"
    - "+.wotgame.cn"
    - "+.wggames.cn"
    - "+.wowsgame.cn"
    - "+.wargaming.net"
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"
    - heartbeat.belkin.com
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - na.b.g-tun.com
    - "+.nflxvideo.net"
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "*.ff14.sdo.com"
    - ff.dorado.sdo.com
    - "*.mcdn.bilivideo.cn"
    - "+.media.dssott.com"
    - shark007.net
    - Mijia Cloud
    - "+.cmbchina.com"
    - "+.cmbimg.com"
    - local.adguard.org
    - "+.sandai.net"
    - "+.n0808.com"
    - "+.uu.163.com"
    - ps.res.netease.com
    - "+.pub.3gppnetwork.org"
    - geoip:cn
    - geoip:private
    - geosite:category-games
    - geosite:cn
    - geosite:geolocation-cn
  nameserver:
    - https://sm2.doh.pub/dns-query#skip-cert-verify=true
    - quic://dns.alidns.com:853#skip-cert-verify=true
    - https://dns.alidns.com/dns-query#h3=true&skip-cert-verify=true
  fallback:
    - https://v.recipes/dns-query#h3=true&skip-cert-verify=true
    - https://dooh.cloudflare-dns.com/dns-query#h3=true&skip-cert-verify=true&ecs=1.1.1.1/24&ecs-override=true
    - https://v.recipes/dns/dns.google/dns-query#h3=true&skip-cert-verify=true
  proxy-server-nameserver:
    - https://v.recipes/dns-query#h3=true&skip-cert-verify=true
    - https://dooh.cloudflare-dns.com/dns-query#h3=true&skip-cert-verify=true&ecs=1.1.1.1/24&ecs-override=true
    - https://v.recipes/dns/dns.google/dns-query#h3=true&skip-cert-verify=true
    - https://sm2.doh.pub/dns-query#skip-cert-verify=true
    - quic://dns.alidns.com:853#skip-cert-verify=true
    - https://dns.alidns.com/dns-query#h3=true&skip-cert-verify=true
  direct-nameserver:
    - https://sm2.doh.pub/dns-query#skip-cert-verify=true
    - https://dns.alidns.com/dns-query#h3=true&skip-cert-verify=true
    - quic://dns.alidns.com:853#skip-cert-verify=true
  direct-nameserver-follow-policy: true
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - geolocation-!cn
    ipcidr:
      - ::/128
      - ::1/128
      - 2001::/32
      - 0.0.0.0/32
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com"
      - "+.msftconnecttest.com"
      - "+.msftncsi.com"
      - "+.org"
  nameserver-policy:
    "+.ndmdhs.com": 1.0.0.1
    "+.dutils.com": 114.114.114.114
    "+.hostbuf.com": 114.114.114.114
    "geosite:category-ads-all": rcode://success
    "+.tw,+.jp":
      - https://v.recipes/dns/doh.dns.sb/dns-query
      - https://v.recipes/dns/dns.google/dns-query
      - tls://1.0.0.1
    "geosite:category-games@cn":
      - tls://dot-pure.onedns.net
      - quic://dns.alidns.com:853
      - https://sm2.doh.pub/dns-query
    "rule-set:WeChat,DNS":
      - tls://dot-pure.onedns.net
      - quic://dns.alidns.com:853
      - https://sm2.doh.pub/dns-query
    "rule-set:AppleMusic,AMusic":
      - https://v.recipes/dns/doh.dns.sb/dns-query
      - https://v.recipes/dns/dns.google/dns-query
      - tls://1.0.0.1
    "geosite:category-ai-!cn,geolocation-!cn":
      - https://v.recipes/dns/doh.dns.sb/dns-query
      - https://v.recipes/dns/dns.google/dns-query
      - tls://1.0.0.1
    "geosite:apple,cloudflare,wikimedia,tiktok,pikpak,github,speedtest,sony,meta,google,microsoft,yahoo":
      - https://v.recipes/dns/doh.dns.sb/dns-query
      - https://v.recipes/dns/dns.google/dns-query
      - tls://1.0.0.1
    "geosite:apple-cn,cn,private":
      - tls://dot-pure.onedns.net
      - quic://dns.alidns.com:853
      - https://sm2.doh.pub/dns-query
    "geoip:google":
      - https://v.recipes/dns/doh.dns.sb/dns-query
      - https://v.recipes/dns/dns.google/dns-query
      - tls://1.0.0.1
    "geoip:cn":
      - quic://dns.alidns.com:853
      - tls://dot-pure.onedns.net
      - https://sm2.doh.pub/dns-query
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    QUIC:
      ports: [443, 8443]
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
  force-domain:
    - geosite:geolocation-!cn
  skip-domain:
    - Mijia Cloud
    - +.mijia.tech
    - dlg.io.mi.com
    - +.oray.com
    - +.sunlogin.net
    - geosite:cn