[custom]

;设置分组标志位
custom_proxy_group=♻️ 手动切换`select`[]DIRECT`.*
custom_proxy_group=🌏 国外网站`select`[]♻️ 手动切换`[]DIRECT`.*
custom_proxy_group=🌏 国内网站`select`[]DIRECT`[]♻️ 手动切换`.*
custom_proxy_group=🐟 漏网之鱼`select`[]♻️ 手动切换`[]DIRECT`.*

;设置规则标志位
ruleset=🌏 国内网站,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml
ruleset=🌏 国内网站,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Download/Download.yaml
ruleset=🌏 国内网站,[]GEOSITE,CN
ruleset=🌏 国外网站,[]GEOSITE,geolocation-!cn
ruleset=🌏 国内网站,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]MATCH

; enable_rule_generator=true
overwrite_original_rules=true

; [common]
append_proxy_type=false
; proxy_subscription=SYSTEM
; proxy_ruleset=SYSTEM
proxy_config=SYSTEM
; get out of here (!
clash_rule_base=https://raw.githubusercontent.com/xuanranran/Clash/refs/heads/main/Clash/base_NoGroups.yaml
exclude_remarks=(到期|剩余流量|时间|官网|产品|平台|更新订阅|客服)
; do you play games?
; exclude_remarks=(G-|游戏)

; [node_pref]
; love tls1.3
tls13_flag=true
; no you don't play games
udp_flag=true
; though useless
tcp_fast_open_flag=true
append_sub_userinfo=true
; no
filter_deprecated_nodes=true
; looks better
clash_proxies_style=block
clash_use_new_field_name=true

; [userinfo]
; useless?
stream_rule=^剩余流量：(.*?)\|总流量：(.*)$|total=$2&left=$1
time_rule=^过期时间：(\d+)-(\d+)-(\d+) (\d+):(\d+):(\d+)$|$1:$2:$3:$4:$5:$6

add_emoji=true
remove_old_emoji=true
emoji=(流量|时间|应急|Yourip|ISP|Traffic|Expire|以下为节点标签介绍|HOME 家宽节点|测试),🏳️‍🌈
emoji=(EMBY),🎥
emoji=(香港|HK|Hong Kong),🇭🇰
emoji=(日本|川日|东京|櫻花雲|東京|大阪|泉日|埼玉|JP|Japan),🇯🇵
emoji=(台灣|台湾|新北|彰化|TW|Taiwan),🇹🇼
emoji=(新加坡|坡|狮城|SG|Singapore),🇸🇬
emoji=(KR|Korea|KOR|首尔|韩|韓),🇰🇷
emoji=(DE|Germany|DEU|法兰克福|德(國|国|意志)|中德|京德),🇩🇪
emoji=(IN|India|IND|印度|孟买|加尔各答|贾坎德|泰米尔纳德),🇮🇳
emoji=(CA|Canada|CAN|加拿大|蒙特利尔|温哥华|楓葉|枫叶),🇨🇦
emoji=(LU|LUX|卢森堡|盧森堡|Luxemburg|Luxembourg),🇱🇺
emoji=(RU|RUS|Russia|Moscow|Petersburg|Siberia|伯力|莫斯科|圣彼得堡|西伯利亚|新西伯利亚|哈巴罗夫斯克|俄罗斯|俄国),🇷🇺
emoji=(TR|TUR|Turkey|Türkiye|土耳其),🇹🇷
emoji=(MYS|MY[^-]|Malaysia|马来|马来西亚|大马|马莱|艾尔迪亚|橡胶和锡的王国),🇲🇾
emoji=(GB|GBR|UK|England|United.*?Kingdom|London|英国|[^-]英|伦敦),🇬🇧
emoji=(AR|ARG|Argentina|阿根廷),🇦🇷
emoji=(BR|BRA|Brazil|Paulo|巴西|圣保罗),🇧🇷
emoji=(AU|AUS|Australia|Sydney|澳大利亚|澳洲|悉尼),🇦🇺
emoji=(美(國|国)|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States),🇺🇸
emoji=(AE|UAE|United Arab Emirates|Dubai|阿联酋|迪拜|阿拉伯联合酋长国),🇦🇪
emoji=(PL|POL|Poland|波兰),🇵🇱
emoji=(FR|FRA|France|Paris|法国|巴黎),🇫🇷
emoji=(BGD|Bengal|Bangladesh|孟加拉),🇧🇩
emoji=(Mauritius|毛里求斯),🇲🇺
emoji=(Rwanda|卢旺达),🇷🇼
emoji=(Libya|利比亚),🇱🇾
emoji=(Morocco|摩洛哥),🇲🇦
emoji=(Puerto Rico|波多黎各),🇵🇷
emoji=(Guatemala|危地马拉),🇬🇹
emoji=(Venezuela|委内瑞拉),🇻🇪
emoji=(Ecuador|厄瓜多尔),🇪🇨
emoji=(Dutch Curacao|Curaçao|荷属库拉索),🇨🇼
emoji=(French Reunion|法属留尼汪),🇷🇪
emoji=(Malta|马耳他),🇲🇹
emoji=(Andorra|安道尔),🇦🇩
emoji=(Vatican|梵蒂冈),🇻🇦
emoji=(Ukraine|乌克兰),🇺🇦
emoji=(Uzbekistan|乌兹别克斯坦),🇺🇿
emoji=(Armenia|亚美尼亚),🇦🇲
emoji=(Nepal|SwissCom|尼泊尔|坎提普尔),🇳🇵
emoji=(Bahrain|巴林),🇧🇭
emoji=(Guam|关岛),🇬🇺
emoji=(阿尔巴尼亚|Albania|AL),🇦🇱
emoji=(Austria|Vienna|奥地利|维也纳|AT),🇦🇹
emoji=(阿塞拜疆|Azerbaijan),🇦🇿
emoji=(波黑共和国|波士尼亚与赫塞哥维纳|Bosnia|Herzegovina),🇧🇦
emoji=(Belgium|比利时),🇧🇪
emoji=(保加利亚|Bulgaria),🇧🇬
emoji=(Switzerland|Zurich|瑞士|苏黎世),🇨🇭
emoji=(智利|Chile),🇨🇱
emoji=(Colombia|哥伦比亚),🇨🇴
emoji=(Costa Rica|哥斯达黎加),🇨🇷
emoji=(塞浦路斯|Cyprus),🇨🇾
emoji=(Czech|捷克),🇨🇿
emoji=(DNK|Denmark|丹麦),🇩🇰
emoji=(爱沙尼亚|Estonia),🇪🇪
emoji=(埃及|Egypt),🇪🇬
emoji=(ESP|Spain|España|Telefonica|西班牙),🇪🇸
emoji=(Europe|欧洲),🇪🇺
emoji=(Finland|Helsinki|芬兰|赫尔辛基),🇫🇮
emoji=(希腊|Greece),🇬🇷
emoji=(格鲁吉亚|Georgia),🇬🇪
emoji=(克罗地亚|Croatia),🇭🇷
emoji=(Hungary|匈牙利),🇭🇺
emoji=(Indonesia|Jakarta|印尼|印度尼西亚|雅加达),🇮🇩
emoji=(Ireland|Dublin|爱尔兰|都柏林),🇮🇪
emoji=(Israel|以色列),🇮🇱
emoji=(马恩岛|Mann),🇮🇲
emoji=(伊朗|Iran),🇮🇷
emoji=(ISL|Iceland|冰岛),🇮🇸
emoji=(Italia|Italy|Milan|意大利|米兰|葡萄酒之国),🇮🇹
emoji=(约旦|Jordan),🇯🇴
emoji=(肯尼亚|Kenya),🇰🇪
emoji=(吉尔吉斯斯坦|Kyrgyzstan),🇰🇬
emoji=(柬埔寨|Cambodia),🇰🇭
emoji=(KP|North Korea|朝鲜),🇰🇵
emoji=(哈萨克斯坦|Kazakhstan),🇰🇿
emoji=(立陶宛|Lietuvos),🇱🇹
emoji=(拉脱维亚|Latvia),🇱🇻
emoji=(Moldova|摩尔多瓦|基希讷乌|奇西瑙|Chisinau|Chișinău),🇲🇩
emoji=(蒙古|Монголулс|Mongolia),🇲🇳
emoji=(北马其顿|Macedonia),🇲🇰
emoji=(Macao|澳门|龙涯门),🇲🇴
emoji=(墨西哥|Mexico),🇲🇽
emoji=(尼日利亚|Nigeria),🇳🇬
emoji=(NLD|Netherland|荷兰|阿姆斯特丹|尼德兰),🇳🇱
emoji=(挪威|Norway),🇳🇴
emoji=(新西兰|纽西兰|New Zealand),🇳🇿
emoji=(Philippines|PH[^-]|菲律宾),🇵🇭
emoji=(Pakistan|巴基斯坦),🇵🇰
emoji=(巴拿马|Panama),🇵🇦
emoji=(秘鲁|Peru),🇵🇪
emoji=(葡萄牙|Portugal),🇵🇹
emoji=(Romania|罗马尼亚),🇷🇴
emoji=(塞尔维亚|Serbia),🇷🇸
emoji=(Arabia|沙特),🇸🇦
emoji=(Sweden|瑞典),🇸🇪
emoji=(斯洛文尼亚|Slovenia),🇸🇮
emoji=(斯洛伐克|Slovensko),🇸🇰
emoji=(Thailand|TH[^-]|泰国|曼谷),🇹🇭
emoji=(突尼斯|Tunisia),🇹🇳
emoji=(乌拉圭|Uruguay),🇺🇾
emoji=(Vietnam|Viet Nam|越南),🇻🇳
emoji=(Africa|南非),🇿🇦
emoji=(塞舌尔|Seychelles),🇸🇨
emoji=(阿曼|Oman),🇴🇲
emoji=(老挝|Laos),🇱🇦
emoji=(缅甸|Myanmar),🇲🇲
emoji=(黎巴嫩|Lebanon),🇱🇧
emoji=(斯里兰卡|Sri Lanka),🇱🇰
emoji=(伊拉克|Iraq),🇮🇶
emoji=(叙利亚|Syria),🇸🇾
emoji=(列支敦士登|Liechtenstein),🇱🇮
emoji=(阿尔及利亚|Algeria),🇩🇿
emoji=(南极|Antarctica|克拉拉的雪糕|AQ),🇦🇶
emoji=(卡塔尔|Qatar),🇶🇦
emoji=(文莱|Brunei),🇧🇳
emoji=(巴拉圭|Paraguay),🇵🇾
emoji=(黑山|Montenegro),🇲🇪
emoji=(直布罗陀|Gibraltar),🇬🇮
emoji=(圣马力诺|San Marino),🇸🇲
emoji=(古巴|cuba),🇨🇺
emoji=(斐济|Fiji),🇫🇯
emoji=(格陵兰|Greenland),🇬🇱
emoji=(开曼群岛|Cayman Islands),🇰🇾
emoji=(马尔代夫|Maldives),🇲🇻
emoji=(不丹|Bhutan),🇧🇹
emoji=(加纳|Ghana),🇬🇭
emoji=(摩纳哥|Monaco),🇲🇨
emoji=(法罗群岛|Faroe Islands),🇫🇴
emoji=(百慕大|Bermuda),🇧🇲
emoji=(牙买加|Jamaica),🇯🇲
emoji=(苏里南|Suriname),🇸🇷
emoji=(佛得角|Cape Verde),🇨🇻
emoji=(东帝汶|East Timor),🇹🇱
emoji=(阿富汗|Afghan),🇦🇫
emoji=(奥兰群岛|Åland),🇦🇽
emoji=(英属维尔京|British Virgin),🇻🇬
emoji=(洪都拉斯|Honduras),🇭🇳
emoji=(尼加拉瓜|Nicaragua),🇳🇮
emoji=(安哥拉|Angola),🇦🇴
emoji=(巴勒斯坦|Palestine),🇵🇸
emoji=(法属圭亚那|Guyane française|French Guiana),🇬🇫
emoji=(多哥|Togo|togo|République togolaise),🇹🇬
emoji=(巴哈马|Bahamas),🇧🇸
emoji=(特立尼达和多巴哥|千里達及托巴哥|Republic of Trinidad and Tobago|Trinidad and Tobago),🇹🇹
emoji=(莫桑比克|Mozambique),🇲🇿
emoji=(也门|Yemen),🇾🇪
emoji=(科威特|Kuwait),🇰🇼
emoji=(土库曼斯坦|Turkmenistan),🇹🇲
emoji=(所罗门群岛|solomon islands),🇸🇧
emoji=(贝宁|Benin),🇧🇯
emoji=(马里|Mali),🇲🇱
emoji=(刚果（金）|刚果家宽|Congo-Kinshasa),🇨🇩
emoji=(喀麦隆|Cameroon),🇨🇲
emoji=(科特迪瓦|象牙海岸|Ivory Coast),🇨🇮
emoji=(斯威士兰|Swaziland),🇸🇿
emoji=(巴巴多斯|Barbados),🇧🇧
emoji=(津巴布韦|Zimbabwe),🇿🇼
emoji=(赤道几内亚|Equatorial Guinea|Guinea Ecuatorial),🇬🇶
emoji=(安提瓜和巴布达|Antigua|Barbuda|Antigua and Barbuda),🇦🇬
emoji=(阿鲁巴|Aruba),🇦🇼
emoji=(苏丹|Sudan),🇸🇩
emoji=(巴布亚新几内亚|Papua|Papua New Guinea),🇵🇬
emoji=(塔吉克斯坦|Tajikistan),🇹🇯
emoji=(汤加|Tonga),🇹🇴
emoji=(海地|Haiti),🇭🇹
emoji=(圭亚那|Guyana),🇬🇾
emoji=(玻利维亚|Bolivia),🇧🇴
emoji=(多米尼克|Dominica),🇩🇲
emoji=(多米尼加|dominican),🇩🇴
emoji=(坦桑尼亚|Tanzania),🇹🇿
emoji=(马达加斯加|Madagascar),🇲🇬
emoji=(格林纳达|Grenada),🇬🇩
emoji=(伯利兹|Belice),🇧🇿
emoji=(布隆迪|Burundi),🇧🇮
emoji=(法属瓜德罗普|Guadeloupe),🇬🇵
emoji=(法属马提尼克|Martinique|maʁtinik),🇲🇶
emoji=(萨尔瓦多|El Salvador),🇸🇻
emoji=(Belarus|白俄罗斯),🇧🇾
emoji=(美属萨摩亚|American Samoa),🇦🇸
emoji=(萨摩亚|Samoa),🇼🇸
emoji=(安圭拉|Anguilla),🇦🇮
emoji=(阿森松岛|Ascension Island),🇦🇨
emoji=(博茨瓦纳|Botswana),🇧🇼
emoji=(布韦岛|Bouvet Island),🇧🇻
emoji=(英属印度洋领地|British Indian Ocean Territory),🇮🇴
emoji=(布基纳法索|Burkina Faso),🇧🇫
emoji=(荷属加勒比区|Caribbean Netherlands),🇧🇶
emoji=(中非共和国|Central African Republic),🇨🇫
emoji=(休达和梅利利亚|Ceuta & Melilla),🇪🇦
emoji=(乍得|Chad),🇹🇩
emoji=(圣诞岛|Christmas Island),🇨🇽
emoji=(克利珀顿岛|Clipperton Island),🇨🇵
emoji=(科科斯（基林）群岛|Cocos (Keeling) Islands),🇨🇨
emoji=(科摩罗|Comoros),🇰🇲
emoji=(刚果|刚果（布）|Congo Brazzaville),🇨🇬
emoji=(库克群岛|Cook Islands),🇨🇰
emoji=(迪戈加西亚|Diego Garcia),🇩🇬
emoji=(吉布提|Djibouti),🇩🇯
emoji=(厄立特里亚|Eritrea),🇪🇷
emoji=(埃塞俄比亚|Ethiopia),🇪🇹
emoji=(欧盟|European Union),🇪🇺
emoji=(福克兰群岛|Falkland Islands),🇫🇰
emoji=(法属波利尼西亚|French Polynesia),🇵🇫
emoji=(法属南部领地|French Southern Territories),🇹🇫
emoji=(加蓬|Gabon),🇬🇦
emoji=(冈比亚|Gambia),🇬🇲
emoji=(根西|Guernsey),🇬🇬
emoji=(几内亚|Guinea),🇬🇳
emoji=(几内亚比绍|Guinea Bissau),🇬🇼
emoji=(泽西|Jersey),🇯🇪
emoji=(基里巴斯|Kiribati),🇰🇮
emoji=(科索沃|Kosovo),🇽🇰
emoji=(莱索托|Lesotho),🇱🇸
emoji=(利比里亚|Liberia),🇱🇷
emoji=(马拉维|Malawi),🇲🇼
emoji=(毛里塔尼亚|Mauritania),🇲🇷
emoji=(马约特|Mayotte),🇾🇹
emoji=(密克罗尼西亚|Micronesia),🇫🇲
emoji=(蒙特塞拉特|Montserrat),🇲🇸
emoji=(纳米比亚|Namibia),🇳🇦
emoji=(瑙鲁|Nauru),🇳🇷
emoji=(新喀里多尼亚|New Caledonia),🇳🇨
emoji=(尼日尔|Niger),🇳🇪
emoji=(纽埃|Niue),🇳🇺
emoji=(诺福克岛|Norfolk Island),🇳🇫
emoji=(北马里亚纳群岛|Northern Mariana Islands),🇲🇵
emoji=(帕劳|Palau),🇵🇼
emoji=(皮特凯恩群岛|Pitcairn Islands),🇵🇳
emoji=(圣多美和普林西比|São Tomé & Príncipe),🇸🇹
emoji=(塞内加尔|Senegal),🇸🇳
emoji=(塞拉利昂|Sierra Leone),🇸🇱
emoji=(荷属圣马丁|Sint Maarten),🇸🇽
emoji=(索马里|Somalia),🇸🇴
emoji=(南乔治亚和南桑威奇群岛|South Georgia & South Sandwich Islands),🇬🇸
emoji=(南苏丹|South Sudan),🇸🇸
emoji=(圣巴泰勒米|St. Barthélemy),🇧🇱
emoji=(圣赫勒拿|St. Helena),🇸🇭
emoji=(圣基茨和尼维斯|St. Kitts & Nevis),🇰🇳
emoji=(圣卢西亚|St. Lucia),🇱🇨
emoji=(法属圣马丁|St. Martin),🇲🇫
emoji=(圣皮埃尔和密克隆|St. Pierre & Miquelon),🇵🇲
emoji=(圣文森特和格林纳丁斯|St. Vincent & Grenadines),🇻🇨
emoji=(斯瓦尔巴和扬马延|Svalbard & Jan Mayen),🇸🇯
emoji=(托克劳|Tokelau),🇹🇰
emoji=(特里斯坦-达库尼亚群岛|Tristan da Cunha),🇹🇦
emoji=(特克斯和凯科斯群岛|Turks & Caicos Islands),🇹🇨
emoji=(图瓦卢|Tuvalu),🇹🇻
emoji=(乌干达|Uganda),🇺🇬
emoji=(联合国|United Nations),🇺🇳
emoji=(美国本土外小岛屿|U.S. Outlying Islands),🇺🇲
emoji=(美属维尔京|U.S. Virgin Islands),🇻🇮
emoji=(瓦努阿图|Vanuatu),🇻🇺
emoji=(瓦利斯和富图纳|Wallis & Futuna),🇼🇫
emoji=(西撒哈拉|Western Sahara),🇪🇭
emoji=(赞比亚|Zambia),🇿🇲
emoji=(马绍尔群岛|Marshall Islands),🇲🇭
emoji=(移动|联通|电信|China|回国|中国[^-]|江苏[^-]|北京[^-]|上海[^-]|广州[^-]|深圳[^-]|杭州[^-]|常州[^-]|徐州[^-]|青岛[^-]|宁波[^-]|镇江[^-]|成都[^-]|back),🇨🇳
